### ISSUE TITLE
Cannot install Kong via homebrew. [Failed installing dependency: https://luarocks.org/luasec-0.6-1.rockspec - Failed cloning git repository.]

### ISSUE THREAD

**Issue by ashishmh** [Kong/homebrew-kong#50]
Hi,
I am trying to install kong via homebrew and getting this error:

```
brew install -vd kong
Updating Homebrew...
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/mashape/homebrew-kong/Formula/kong.rb
==> Installing kong from mashape/kong
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/mashape/homebrew-kong/Formula/openresty.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pcre.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/mashape/homebrew-kong/Formula/luarocks.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/bin/sandbox-exec -f /tmp/homebrew20171009-49198-m2xovk.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/mashape/homebrew-kong/Formula/kong.rb --verbose --debug
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/mashape/homebrew-kong/Formula/kong.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/mashape/homebrew-kong/Formula/openresty.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pcre.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/mashape/homebrew-kong/Formula/luarocks.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
==> Downloading https://bintray.com/kong/kong-community-edition-src/download_file?file_path=kong-community-edition-0.11.0.tar.gz
Already downloaded: /Users/ashish.maheshwari/Library/Caches/Homebrew/kong-0.11.0.tar.gz
==> Verifying kong-0.11.0.tar.gz checksum
tar xzf /Users/ashish.maheshwari/Library/Caches/Homebrew/kong-0.11.0.tar.gz
==> Patching
patching file kong/templates/kong_defaults.lua
==> luarocks-5.1 --tree=/usr/local/Cellar/kong/0.11.0 make OPENSSL_DIR=/usr/local/opt/openssl
Missing dependencies for kong 0.11.0-0:
   luasec == 0.6 (not installed)
   luasocket == 3.0-rc1 (not installed)
   penlight == 1.5.4 (not installed)
   lua-resty-http == 0.08 (not installed)
   lua-resty-jit-uuid == 0.0.5 (not installed)
   multipart == 0.5 (not installed)
   version == 0.2 (not installed)
   kong-lapis == 1.6.0.1 (not installed)
   lua-cassandra == 1.2.3 (not installed)
   pgmoon == 1.8.0 (not installed)
   luatz == 0.3 (not installed)
   lua_system_constants == 0.1.2 (not installed)
   lua-resty-iputils == 0.2.1 (not installed)
   luacrypto == 0.3.2 (not installed)
   luasyslog == 1.0.0 (not installed)
   lua_pack == 1.0.5 (not installed)
   lua-resty-dns-client == 0.6.0 (not installed)
   lua-resty-worker-events == 0.3.0 (not installed)
   lua-resty-mediador == 0.1.2 (not installed)

kong 0.11.0-0 depends on luasec == 0.6 (not installed)
Installing https://luarocks.org/luasec-0.6-1.rockspec
Missing dependencies for luasec 0.6-1:
   luasocket (not installed)

luasec 0.6-1 depends on luasocket (not installed)
Installing https://luarocks.org/luasocket-3.0rc1-2.src.rock
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/buffer.c -o src/buffer.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/auxiliar.c -o src/auxiliar.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/options.c -o src/options.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/timeout.c -o src/timeout.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/io.c -o src/io.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/usocket.c -o src/usocket.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/unix.c -o src/unix.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -bundle -undefined dynamic_lookup -all_load -o socket/unix.so -L/usr/local/opt/openresty/luajit/lib src/buffer.o src/auxiliar.o src/options.o src/timeout.o src/io.o src/usocket.o src/unix.o
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/buffer.c -o src/buffer.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/auxiliar.c -o src/auxiliar.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/options.c -o src/options.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/timeout.c -o src/timeout.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/io.c -o src/io.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/usocket.c -o src/usocket.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/serial.c -o src/serial.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -bundle -undefined dynamic_lookup -all_load -o socket/serial.so -L/usr/local/opt/openresty/luajit/lib src/buffer.o src/auxiliar.o src/options.o src/timeout.o src/io.o src/usocket.o src/serial.o
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/luasocket.c -o src/luasocket.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/timeout.c -o src/timeout.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/buffer.c -o src/buffer.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/io.c -o src/io.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/auxiliar.c -o src/auxiliar.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/options.c -o src/options.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/inet.c -o src/inet.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/except.c -o src/except.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/select.c -o src/select.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/tcp.c -o src/tcp.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/udp.c -o src/udp.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/usocket.c -o src/usocket.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -bundle -undefined dynamic_lookup -all_load -o socket/core.so -L/usr/local/opt/openresty/luajit/lib src/luasocket.o src/timeout.o src/buffer.o src/io.o src/auxiliar.o src/options.o src/inet.o src/except.o src/select.o src/tcp.o src/udp.o src/usocket.o
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/mime.c -o src/mime.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -bundle -undefined dynamic_lookup -all_load -o mime/core.so -L/usr/local/opt/openresty/luajit/lib src/mime.o
No existing manifest. Attempting to rebuild...
luasocket 3.0rc1-2 is now installed in /usr/local/Cellar/kong/0.11.0 (license: MIT)

Cloning into 'luasec'...
fatal: unable to connect to github.com:
github.com[0: 192.30.255.113]: errno=Operation timed out
github.com[1: 192.30.255.112]: errno=Operation timed out


Error: Failed installing dependency: https://luarocks.org/luasec-0.6-1.rockspec - Failed cloning git repository.
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: luarocks-5.1 --tree=/usr/local/Cellar/kong/0.11.0 make OPENSSL_DIR=/usr/local/opt/openssl
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1
==> Kept temporary files
Temporary files retained at /tmp/kong-20171009-49200-1d42inx

==> Formula
Tap: mashape/kong
Path: /usr/local/Homebrew/Library/Taps/mashape/homebrew-kong/Formula/kong.rb
==> Configuration
HOMEBREW_VERSION: 1.3.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 91ab116ace7f4f97d3440190463c93be9ec6d675
Last commit: 23 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2cbac5ff6ec861e9ff0ab89937c667c4be9d9722
Core tap last commit: 23 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.6.3 => /usr/local/bin/git
Perl: /usr/bin/perl
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_102, 1.7.0_80
macOS: 10.12.6-x86_64
Xcode: 9.0
CLT: 9.0.0.0.1.1504363082
X11: N/A
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/openssl:/usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
MACOSX_DEPLOYMENT_TARGET: 10.12
PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/openssl/bin:/usr/local/opt/pcre/bin:/usr/local/opt/openresty/bin:/usr/local/opt/luarocks/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: mashape/kong/kong 0.11.0 did not build
Logs:
     /Users/ashish.maheshwari/Library/Logs/Homebrew/kong/00.options.out
     /Users/ashish.maheshwari/Library/Logs/Homebrew/kong/01.openssl
     /Users/ashish.maheshwari/Library/Logs/Homebrew/kong/01.openssl.cc
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/mashape/homebrew-kong/issues

These open issues may also help:
lua.h version mismatch (interpreter: ; lua.h: 5.1) https://github.com/Mashape/homebrew-kong/issues/49
```

To solve this, i tried installing luasec manually using luarocks:
```luarocks install luasec OPENSSL_INCDIR=/usr/local/Cellar/openssl/1.0.2l/include```
and got the following response:
```luasec 0.7alpha-1 is now installed in /usr/local/opt/kong (license: MIT)```

After this when I try installing kong via brew again, i get the following error:
```
brew install -vd kong
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/mashape/homebrew-kong/Formula/kong.rb
Error: /usr/local/opt/kong is not a valid keg
/usr/local/Homebrew/Library/Homebrew/keg.rb:185:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:214:in `new'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:214:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:110:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:110:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```

If i delete /usr/local/opt/kong, then brew again throws the first error.
```Error: Failed installing dependency: https://luarocks.org/luasec-0.6-1.rockspec - Failed cloning git repository.```

**Comment by fatinWasta** [comment]
Going through same issues
![screen shot 2017-10-14 at 3 15 56 pm](https://user-images.githubusercontent.com/14032221/31574718-a7792c44-b0f2-11e7-9b04-0593ccce9640.png)

**Comment by dapangmao** [comment]
Same here

**Comment by daltk** [comment]
$ brew install kong
Updating Homebrew...
==> Installing kong from mashape/kong
==> Downloading https://bintray.com/kong/kong-community-edition-src/download_file?file_path=kong-community-edition-0.11.
Already downloaded: /Users/ncs/Library/Caches/Homebrew/kong-0.11.0.tar.gz
==> Patching
patching file kong/templates/kong_defaults.lua
==> luarocks-5.1 --tree=/usr/local/Cellar/kong/0.11.0 make OPENSSL_DIR=/usr/local/opt/openssl
Last 15 lines from /Users/ncs/Library/Logs/Homebrew/kong/01.openssl:
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/udp.c -o src/udp.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/usocket.c -o src/usocket.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -bundle -undefined dynamic_lookup -all_load -o socket/core.so -L/usr/local/opt/openresty/luajit/lib src/luasocket.o src/timeout.o src/buffer.o src/io.o src/auxiliar.o src/options.o src/inet.o src/except.o src/select.o src/tcp.o src/udp.o src/usocket.o
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c src/mime.c -o src/mime.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -bundle -undefined dynamic_lookup -all_load -o mime/core.so -L/usr/local/opt/openresty/luajit/lib src/mime.o
No existing manifest. Attempting to rebuild...
luasocket 3.0rc1-2 is now installed in /usr/local/Cellar/kong/0.11.0 (license: MIT)

Cloning into 'luasec'...
fatal: unable to connect to github.com:
github.com[0: 192.30.255.113]: errno=Operation timed out
github.com[1: 192.30.255.112]: errno=Operation timed out


Error: Failed installing dependency: https://luarocks.org/luasec-0.6-1.rockspec - Failed cloning git repository.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/mashape/homebrew-kong/issues

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:220:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:178:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:278:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:225:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:238:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:369:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:365:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:419:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:135:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'

**Comment by TomJahncke** [comment]
Same error for me

**Comment by DBozz** [comment]
Same issue here

**Comment by Flynn81** [comment]
Same issue here as well

**Comment by pactera-cart-zhangtao** [comment]
Same issue here

**Comment by pactera-cart-zhangtao** [comment]
==> Installing kong from mashape/kong
==> Downloading https://bintray.com/kong/kong-community-edition-src/download_fil
Already downloaded: /Users/zhangtao/Library/Caches/Homebrew/kong-0.11.2.tar.gz
==> Patching
patching file kong/templates/kong_defaults.lua
==> luarocks-5.1 --tree=/usr/local/Cellar/kong/0.11.2 make OPENSSL_DIR=/usr/loca
Last 15 lines from /Users/zhangtao/Library/Logs/Homebrew/kong/01.openssl:
kong-lapis 1.6.0.1-1 depends on mimetypes (not installed)
Installing https://luarocks.org/mimetypes-1.0.0-1.src.rock
mimetypes 1.0.0-1 is now installed in /usr/local/Cellar/kong/0.11.2 (license: MIT/X11)

kong-lapis 1.6.0.1-1 depends on pgmoon (not installed)
Installing https://luarocks.org/pgmoon-1.8.0-1.src.rock
pgmoon 1.8.0-1 is now installed in /usr/local/Cellar/kong/0.11.2 (license: MIT)

Cloning into 'lapis'...
fatal: unable to connect to github.com:
github.com[0: 192.30.255.112]: errno=Operation timed out
github.com[1: 192.30.255.113]: errno=Operation timed out


Error: Failed installing dependency: https://luarocks.org/kong-lapis-1.6.0.1-1.rockspec - Failed cloning git repository.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/mashape/homebrew-kong/issues

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:220:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:178:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:278:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:225:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:238:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:369:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:365:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:419:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'

**Comment by mattbrewer** [comment]
I had this issue, but it was because my corporate proxy blocking github.com. Once I connected to a different network, I was able to complete the installation.

**Comment by hanwenbo** [comment]
I also met

**Comment by pkvov** [comment]
i have same problem. and i uses proxychains4 set a command line proxy to fixed this

**Comment by kikito** [comment]
Hi, I am closing this issue because of lack of activity. If you think it is still unresolved, please reopen with the requested information. Thanks!
