### ISSUE TITLE
Error: Failed installing dependency: https://luarocks.org/luatz-0.3-1.all.rock - Could not fetch rock file: Error fetching file: Failed downloading https://luarocks.org/luatz-0.3-1.all.rock - luatz-0.3-1.all.rock

### ISSUE THREAD

**Issue by hanwenbo** [Kong/homebrew-kong#54]
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/mashape/homebrew-kong/issues

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:220:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:178:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:278:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:225:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:238:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:369:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:365:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:419:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'

**Comment by hanwenbo** [comment]
I don't know why, but the company has been having this problem in the afternoon. I go home and use the home network, which seems to have something to do with the Internet.
