### ISSUE TITLE
Error: The `brew link` step did not complete successfully

### ISSUE THREAD

**Issue by hanwenbo** [Kong/homebrew-kong#55]
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/nginx
Target /usr/local/bin/nginx
is a symlink belonging to nginx. You can unlink it:
  brew unlink nginx

To force the link and overwrite all conflicting files:
  brew link --overwrite openresty

To list all files that would be deleted:
  brew link --overwrite --dry-run openresty

Possible conflicting files are:
/usr/local/bin/nginx -> /usr/local/Cellar/nginx/1.10.2_1/bin/nginx
==> Summary
🍺  /usr/local/Cellar/openresty/1.11.2.4: 287 files, 5.7MB, built in 1 minute 14 seconds
==> Installing mashape/kong/kong dependency: mashape/kong/luarocks
==> Downloading https://luarocks.org/releases/luarocks-2.4.2.tar.gz
==> Downloading from http://luarocks.github.io/luarocks/releases/luarocks-2.4.2.tar.gz
######################################################################## 100.0%
==> Patching
patching file Makefile
==> ./configure --prefix=/usr/local/Cellar/luarocks/2.4.2 --rocks-tree=/usr/local/opt/kong --sysconfdir=/usr/local/Cellar/luarocks/2.4.2/etc --with-lua=/usr/loc
==> make build
==> make install
==> Caveats
Rocks will be installed to: /usr/local/opt/kong
==> Summary
🍺  /usr/local/Cellar/luarocks/2.4.2: 78 files, 472.9KB, built in 11 seconds
==> Installing mashape/kong/kong
==> Downloading https://bintray.com/kong/kong-community-edition-src/download_file?file_path=dists%2Fkong-community-edition-0.11.2.tar.gz
==> Downloading from https://dl.bintray.com/kong/kong-community-edition-src/dists/kong-community-edition-0.11.2.tar.gz?expiry=1514342323805&signature=eRpBg9BhUg
######################################################################## 100.0%
==> Patching
patching file kong/templates/kong_defaults.lua
==> luarocks-5.1 --tree=/usr/local/Cellar/kong/0.11.2 make OPENSSL_DIR=/usr/local/opt/openssl
Last 15 lines from /Users/hanwenbo/Library/Logs/Homebrew/kong/01.openssl:
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

lua-cassandra 1.2.3-0 is now installed in /usr/local/Cellar/kong/0.11.2 (license: MIT)

kong 0.11.2-0 depends on luatz == 0.3 (not installed)
Installing https://luarocks.org/luatz-0.3-1.all.rock

Error: Failed installing dependency: https://luarocks.org/luatz-0.3-1.all.rock - Could not fetch rock file: Error fetching file: Failed downloading https://luarocks.org/luatz-0.3-1.all.rock - luatz-0.3-1.all.rock

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/mashape/homebrew-kong/issues

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:220:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:178:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:278:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:225:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:238:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:369:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:365:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:419:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'

**Comment by hanwenbo** [comment]
Why replace nginx ？
