### ISSUE TITLE
`raise_api_error': curl failed!  (GitHub::Error)

### ISSUE THREAD

**Issue by hanwenbo** [Kong/homebrew-kong#56]
brew install kong
==> Installing kong from mashape/kong
==> Downloading https://bintray.com/kong/kong-community-edition-src/download_file?file_path=dists%2Fkong-community-edition-0.11.2.tar.gz
Already downloaded: /Users/hanwenbo/Library/Caches/Homebrew/kong-0.11.2.tar.gz
==> Patching
patching file kong/templates/kong_defaults.lua
==> luarocks-5.1 --tree=/usr/local/Cellar/kong/0.11.2 make OPENSSL_DIR=/usr/local/opt/openssl
Last 15 lines from /Users/hanwenbo/Library/Logs/Homebrew/kong/01.openssl:
   pgmoon == 1.8.0 (not installed)
   luatz == 0.3 (not installed)
   lua_system_constants == 0.1.2 (not installed)
   lua-resty-iputils == 0.3.0 (not installed)
   luacrypto == 0.3.2 (not installed)
   luasyslog == 1.0.0 (not installed)
   lua_pack == 1.0.5 (not installed)
   lua-resty-dns-client == 0.6.2 (not installed)
   lua-resty-worker-events == 0.3.0 (not installed)
   lua-resty-mediador == 0.1.2 (not installed)

kong 0.11.2-0 depends on luasec == 0.6 (not installed)
Installing https://luarocks.org/luasec-0.6-2.src.rock

Error: Failed installing dependency: https://luarocks.org/luasec-0.6-2.src.rock - Could not fetch rock file: Error fetching file: Failed downloading https://luarocks.org/luasec-0.6-2.src.rock - luasec-0.6-2.src.rock

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/mashape/homebrew-kong/issues

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:220:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:178:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:278:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:225:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:238:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:369:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:365:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:419:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'

**Comment by hanwenbo** [comment]
I don't know why, but the company has been having this problem in the afternoon. I go home and use the home network, which seems to have something to do with the Internet.
