### ISSUE TITLE
brew install kong fails (0.14.1)

### ISSUE THREAD

**Issue by wshirey** [Kong/homebrew-kong#83]
```
$ brew tap kong/kong
==> Tapping kong/kong
Cloning into '/usr/local/Homebrew/Library/Taps/kong/homebrew-kong'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
Tapped 3 formulae (34 files, 31.8KB).

$ brew install kong -vd
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/kong/homebrew-kong/Formula/kong.rb
Error: /usr/local/opt/kong is not a valid keg
/usr/local/Homebrew/Library/Homebrew/keg.rb:195:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:242:in `new'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:242:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:126:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:126:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

**Comment by kikito** [comment]
Hi, I am closing this issue because of lack of activity. If you think it is still unresolved, please reopen with the requested information. Thanks!
