### ISSUE TITLE
brew install kong  failed

### ISSUE THREAD

**Issue by steavenMonkey** [Kong/homebrew-kong#88]
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:252:in `raise_api_error': curl failed!   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current (GitHub::Error)
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:45 --:--:--     0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.github.com:443
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:206:in `open_api'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:324:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:257:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:270:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:372:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:368:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:422:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:127:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:17:in `<main>'

**Comment by tholu** [comment]
Looks like a network issue, or can you reproduce this error?

**Comment by kikito** [comment]
Hi, I am closing this issue because of lack of activity. If you think it is still unresolved, please reopen with the requested information. Thanks!
